### ISSUE TITLE
Not really an issue..

### ISSUE THREAD

**Issue by ItsCEED** [mattrberry/csgoSkinStatistics#1]
First of all, congratzz! You did a great job!

And a small request.. A Blue % at case hardned skins would be nice!

**Comment by mattrbeck** [comment]
@ItsCEED Do other services do this? Or do you know of a public database or api for this?

It would be a great feature, but I don't really want to deal with getting my hands on every single case hardened screenshot in the game myself. The image processing wouldn't be trivial, but I don't see it being too challenging. I have tried using the metjm database in the past to grab all of the screenshots, but it too quickly clears out old screenshots which makes it challenging to accumulate any reasonable number of them. I guess I could just start grabbing them as they come available, but at this point it just doesn't seem like a good use of my time for what would be gained.

Again, let me know if you know of any public database or api and I'd happily add it! Or even if you have a collection of all the images that I can process.
