### ISSUE TITLE
Use `bootstrap_from_webapi()` to get CM server list instead of using a built-in list

### ISSUE THREAD

**Issue by Luluno01** [mattrberry/csgoSkinStatistics#4]
The built-in CM server list is out-dated, please use `client.cm_servers.bootstrap_from_webapi()` to get latest CM server list.

**Comment by mattrbeck** [comment]
Can you provide some more context on this? Why does this need to be done? I don't see it referenced in the [steam](steam.readthedocs.io) docs.

**Comment by Luluno01** [comment]
Because if you are not using this method to get the CM server list, you will have a hard time connecting to those possibly deprecated CM servers, which are listed in the **out-dated** built-in CM server list. To put it simply, by default, `steam.core.cm` will use a built-in CM server list, which is out-dated and the servers listed are not guaranteed to be available (most of them are unreachable in my case), while the server list fetched from Steam's Web API (by calling `client.cm_servers.bootstrap_from_webapi()`) is definitely the latest and the listed servers are guaranteed by Steam itself to be available (unless being blocked somehow).

If you want documentation about that method, see [here](https://steam.readthedocs.io/en/stable/api/steam.core.cm.html?highlight=bootstrap#steam.core.cm.CMServerList.bootstrap_from_webapi).

**Comment by mattrbeck** [comment]
Done.
