### ISSUE TITLE
Add Steam Guard Code and sentry file support

### ISSUE THREAD

**Issue by Luluno01** [mattrberry/csgoSkinStatistics#5]
I just can't log onto the CM server without providing the `SteamClient` instance an `auth_code`, which is sent to me by email from Steam. However, there is no prompt where I can enter that code. I checked the ValvePython/Steam [documentation](https://steam.readthedocs.io/en/latest/api/steam.client.html?highlight=auth_code), and add an event listener listening to `auth_code_required` event just like the example handler in that documentation. However, after the first attempt, it prompts every time it tries to log on. I do enter the Steam Guard code, but it is still asking me for a code.

As for the `sentry file`, which is found in the documentation by me, seems to be able to bypass the requirement of Steam Guard code. However, I have no idea what the sentry file is.

Hope your support. :P

**Comment by mattrbeck** [comment]
I'll take a look at supporting 2fa.

**Comment by Luluno01** [comment]
And don't forget Steam Guard code (which is sent to the user by email) pls :). Thx.

**Comment by mattrbeck** [comment]
2fa support has been added in the latest commit.
